# Generated by Django 5.0.6 on 2024-06-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('qualifications', models.TextField()),
                ('hire_date', models.DateField()),
                ('gender', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
