# Generated by Django 5.0.6 on 2024-07-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_fee',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_materials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_outline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='grading_system',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
