# Generated by Django 5.0.6 on 2024-07-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='class_code',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='course_code',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='immediate_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='student_pics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
